services:

#  # Spring Boot application
#  app:
#    image: your-app-image:latest  # Replace with your app's Docker image
#    container_name: spring_boot_app
#    ports:
#      - "8080:8080"  # Mapping the application port
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dlyk?useUnicode=true&characterEncoding=utf8&useSSL=false
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_REDIS_HOST: redis
#      SPRING_REDIS_PORT: 6379
#      SPRING_REDIS_PASSWORD: root
#    depends_on:
#      - mysql
#      - redis
#    networks:
#      - app-network

  # MySQL database
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dlyk
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"  # Exposing the MySQL port
    networks:
      - app-network

  # Redis service
  redis:
    image: redis:latest
    container_name: redis_server
    command: redis-server --requirepass root  # Setting Redis password
    ports:
      - "6379:6379"  # Exposing Redis port
    networks:
      - app-network

volumes:
  mysql-data:  # Persistent volume for MySQL data

networks:
  app-network:
    driver: bridge